language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: sRpLeMAtIKrSs+FyZd8ouj2J+2MREnI7pEfbdgEdbpUHwpFfZM/gs031cGdp/ortWTMiyQxsbCvtz/Yly66ZKFGkdaXVCv/m4+UCnjsvUWA/eScivW320gJlzZkq4X1yP7T1+mNftnzmTUn6esBHLTxxHGRyvSzOSxMXbsV3jxYGiOnX3F97K9qevprFtPaZPXUAhNio0EZhkTb1RoUUWjavJorQ0lC1l40U3CgAI/DYxeDdHzxBEINa6h96g3ko89sQJHOYT74qOcOV1OgjkrUczo/VPPoDN3P9Jlqx3ftepp5cpBdUAD2UJH6qLo1+4IHVSnaaE1CgPkPsQe9nKAbNkek6k1EJvbhkAv0P0wWBH85QE7/3CkuMxtknaTjN50PMsaM0ikFkul8FOo/E8WJlU9u9WuHw2Sk4l2Yj8P0nYY/CUypM8x9bEhCKw/5x94xVU3cgo6qkZiDmCoyqX4jQAwGnRiE02vTmf5Qrn01iI5RuImINFF+HvIN5vLN1W1I/zciIHt9vqvZ6rter34PEEua4kSBCm/Xv07kRxHE9W7B90VYsz0XS9K48E3Q2htYOiMIQ7aiiVxkd6FjuqzbUOWwZlD/CD5At8NGEAYAzWw2st1qm/AwkFMGyJ61ZbFWIUJ9wVO0xO/y4/OJak1ZCAoo8MHHalwzWm43jg3Q=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: RULwJwNFdBtjRpbhL5pXlNDHRjWkz/v8YKqEkgnTiz5TYqjQIs2toMrq2LfeaO9hDts6LiLUoWUQyrVICypeXc8MtyiaQHxseWGwJmIrfHYzxDMjfP0s96A0KzzyuspoUK+Z5LsvYGgDDvVS8MzVq7C5iBqjeVddhmSkacy3hD39RsvOwenGoTdNyLYQ0Nbge0FoSq21ElIemkuoSsSfFuqbsv4LG5hdof+FHxXPqQRCv7lyctpVGiJlFWcByWE/emgfkE3tBqwlnsL0FbiGRIRSdY/HBNNPIFhO4YGtSri/KwF8NhHGg9Dsl7BcykD1PS2qol4ZT9NhLe9Rrk387rmSRkr37ogbwWZYmrzRVVwlBcGkjp1kYnr8KbhHQtzF//cdBGz54skI5XN71unxZsSOqO+utEtf0Ui24CzMpm0G3dfUzCaaxzc/49QBmxSu04u69+l/y5GP7/xWzvVsg6EBPnWVzRgNPOJuNbnoq3Kh7YPdEJ91a11lAVB9C9Eee41bWmw+Tn1vq/DZRPBAQto10/9nTceMBBW9azsI/Hdpd6I+6LB/aJiymGkVByp8/I8apGZawkunRq/MBnpRuycHYXCz+bd8szXvhwHJ8AlBJ2eunFhQBddBFJ0+neevBy77qq5iSW+0MhZQHAV2oyQkr0DUdxjukDCfABj67w0=
    on:
      tags: true
